name: Deploy site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up actions for aws deployment
      - name: Checkout
        uses: actions/checkout@v3

      # Set up actions for building on github
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies and build project
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build

      # Configure the AWS stuff
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Deploy the project
      - name: Deploy
        # run: aws s3 sync ./SOURCE_DIR s3://BUCKET_NAME
        run: aws s3 sync ./build/ s3://nataliesoltis.com
